### ISSUE TITLE
Highlight JavaScript Object names and keys?

### ISSUE THREAD

**Issue by dman777** [tpope/vim-vividchalk#11]
I love this color scheme. I am using it for JavaScript. 

How can I make the Object names, such as `_initFirstView` and `Polymer` in `Polymer.dom(this.root).querySelectorAll('paper-listbox')` colored? There is to much  green here

![foo](https://user-images.githubusercontent.com/887815/42333771-3efcc404-8041-11e8-93c1-54624e2f738d.jpg)

**Comment by tpope** [comment]
How does it look with the default color scheme? Purple is the default comment color and since it's happening for strings rather than comments, something has clearly gone horribly wrong.

**Comment by dman777** [comment]
Thank you for your reply. Here it is with no color themes...

![foo](https://user-images.githubusercontent.com/887815/42340585-164cc602-8056-11e8-9f71-be86e0198781.jpg)

**Comment by tpope** [comment]
Yeah so that's just as ugly, it's not a vividchalk issue. One thing you might try is the following command in a few spots to see if you can figure out where that highlighting is really coming from:

    echo map(synstack(line('.'), col('.')), 'synIDattr(v:val,"name")')
