### ISSUE TITLE
Autocompletion low contrast

### ISSUE THREAD

**Issue by lpoirothattermann** [tpope/vim-vividchalk#12]
Hi

Contrast between blue background and black text is low, could be hard to read on some screen.
![Screenshot 2023-03-19 at 16 19 59](https://user-images.githubusercontent.com/68006124/226186056-c67aae92-7301-479b-a1b1-8092d418d097.png)

What do you think about ?

**Comment by tpope** [comment]
I'm seeing white text there. Can you report back on the output of `:verbose highlight Pmenu`?

**Comment by lpoirothattermann** [comment]
This is ```:verbose highlight Pmenu```

![Screenshot 2023-03-21 at 19 35 58](https://user-images.githubusercontent.com/68006124/226708584-e0a67ef3-7e14-4c79-9144-2ab34d551f1c.png)

```guigf``` is set to ```White```, that's weird

**Comment by lpoirothattermann** [comment]
Hi,

I fixed it.
```
vim.api.nvim_set_hl(0, "CmpItemAbbr", { link = "Pmenu"})
vim.api.nvim_set_hl(0, "CmpItemKind", { link = "Pmenu"})
vim.api.nvim_set_hl(0, "CmpItemMenu", { link = "Pmenu"})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { link = "String"})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { link = "String"})
```
